version: '3.8'

services:
  app:
    build:
      context: .
      args:
        - NEXT_PUBLIC_TOKEN=${NEXT_PUBLIC_TOKEN}
    container_name: crypto-dashboard
    ports:
      - '3000:3000'
    env_file:
      - .env
    environment:
      - NEXT_PUBLIC_TOKEN=${NEXT_PUBLIC_TOKEN}
      - NEXT_PUBLIC_API_URL=${NEXT_PUBLIC_API_URL}
      - NEXT_PUBLIC_API_KEY=${NEXT_PUBLIC_API_KEY}
    restart: unless-stopped
